version: '3.8'

services:
  hms-app:
    image: ghcr.io/boggavacs/hms-app:1.0  
    container_name: hms-app-container
    restart: unless-stopped
    ports:
      - "3003:3000"
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - NODE_ENV=production
    command: /bin/sh -c "npm install --include=dev && npm run build && npm start"

volumes:
  node_modules: