# This is a basic workflow to help you get started with Actions

name: Build & Deploy HMS-UI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: login to hub
        uses: docker/login-action@v2
        with:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push
        uses: docker/login-action@v2
        with:
          context: .
          push: true
          tags: boggavacs/hms-ui:latest
